CREATE TABLE ACCOUNTS (
	ACCOUNT_EMAIL VARCHAR(50) NOT NULL PRIMARY KEY,
	ACCOUNT_PASSWORD VARCHAR(40) NOT NULL,
	PERSON_ID VARCHAR(36) NOT NULL
);

CREATE TABLE DOCTORS (
	PERSON_ID VARCHAR(36) NOT NULL PRIMARY KEY,
	PERSON_FIRST_NAME VARCHAR(30),
	PERSON_LAST_NAME VARCHAR(30),
	PERSON_PHONE_NUMBER VARCHAR(30),
	DOCTOR_GENDER VARCHAR(30),
	DOCTOR_SPECIALITY_ID INTEGER NOT NULL
);

CREATE TABLE SPECIALITIES (
	SPECIALITY_ID INTEGER NOT NULL PRIMARY KEY,
	SPECIALITY_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE SECRETARIES (
	PERSON_ID VARCHAR(36) NOT NULL PRIMARY KEY,
	PERSON_FIRST_NAME VARCHAR(25) NOT NULL,
	PERSON_LAST_NAME VARCHAR(25) NOT NULL,
	PERSON_PHONE_NUMBER VARCHAR(14),
	CONFIRMED BOOLEAN,
	DOCTOR_ID VARCHAR(36) NOT NULL
);

CREATE TABLE DOCUMENTS (
	DOCUMENT_NAME VARCHAR(30) NOT NULL,
	DOCUMENT_DESCRIPTION VARCHAR(500),
	DOCUMENT_DATE DATE NOT NULL,
	DOCUMENT_FILE_PATH VARCHAR(200) NOT NULL,
	DOCUMENT_EXTENSION VARCHAR(30) NOT NULL,
	DOCTOR_ID VARCHAR(36) NOT NULL
);

CREATE TABLE PATIENTS (
	PATIENT_ID VARCHAR(36) PRIMARY KEY,
	PATIENT_FIRST_NAME VARCHAR(50) NOT NULL,
	PATIENT_LAST_NAME VARCHAR(36) NOT NULL,
	PATIENT_GENDER VARCHAR(10),
	PATIENT_BIRTHDAY DATE NOT NULL,
	PATIENT_PROFESSION VARCHAR(50),
	PATIENT_PHONE_NUMBER VARCHAR(50),
	PATIENT_EMAIL VARCHAR(50),
	PATIENT_ADDRESS VARCHAR(150),
	PATIENT_INSURANCE_CARD_NUMBER VARCHAR(100),
	DOCTOR_ID VARCHAR(36) NOT NULL
);

CREATE TABLE MEDIAS (
	MEDIA_DATE DATE,
	MEDIA_DESCRIPTION TEXT,
	MEDIA_FILE_PATH VARCHAR(200) NOT NULL,
	MEDIA_FILE_EXTENSION VARCHAR(20) NOT NULL,
    MEDIA_TYPE VARCHAR(20) NOT NULL,
	PATIENT_ID VARCHAR(36) NOT NULL
);

CREATE TABLE APPOINTMENTS (
	APPOINTMENT_ID VARCHAR(36) PRIMARY KEY,
	APPOINTMENT_DAY DATE NOT NULL,
	APPOINTMENT_TIME TIME NOT NULL,
	PATIENT_ID VARCHAR(36) NOT NULL
);

CREATE TABLE REASONS (
	REASON_DESCRIPTION TEXT,
	APPOINTMENT_ID VARCHAR(36) NOT NULL
);

CREATE TABLE PARACLINICS (
	PARACLINIC_DESCRIPTION TEXT,
	APPOINTMENT_ID VARCHAR(36) NOT NULL
);

CREATE TABLE ANALYSIS_TYPE (
	ANALYSIS_TYPE_ID INTEGER PRIMARY KEY,
	ANALYSIS_TYPE_NAME VARCHAR(500) NOT NULL
);

CREATE TABLE ANALYSIS (
	ANALYSIS_DATE DATE,
	ANALYSIS_RESULT VARCHAR(30) NOT NULL,
	ANALYSIS_TYPE_ID INTEGER NOT NULL,
	PATIENT_ID VARCHAR(36)
);

CREATE TABLE DISEASES (
	DISEASE_ID INTEGER PRIMARY KEY,
	DISEASE_NAME VARCHAR(200) NOT NULL
);

CREATE TABLE DISEASE_PATIENT (
	DISEASE_ID INTEGER NOT NULL,
	PATIENT_ID VARCHAR(36) NOT NULL
);

CREATE TABLE ANTECEDENTS (
	ANTECEDENT_TYPE VARCHAR(20) NOT NULL,
	ANTECEDENT_DESCRIPTION TEXT,
	ANTECEDENT_START_DATE DATE NOT NULL,
	ANTECEDENT_RECOVERY_DATE DATE NOT NULL,
	PATIENT_ID VARCHAR(36) NOT NULL
);

CREATE TABLE CONSULTATIONS (
	CONSULTATION_ID VARCHAR(36) PRIMARY KEY,
	CONSULTATION_DATE DATE NOT NULL,
	CONSULTATION_ANAMNESIS TEXT,
	CONSULTATION_PHEX TEXT,
	CONSULTATION_DIAG TEXT,
	CONSULTATION_PRICE DOUBLE(10, 2),
	PATIENT_ID VARCHAR(36) NOT NULL
);

CREATE TABLE OBSERVATIONS (
	OBSERVATION_DESCRIPTION TEXT,
	CONSULTATION_ID VARCHAR(36) NOT NULL
);

CREATE TABLE PRESCRIPTIONS (
	CONSULTATION_ID VARCHAR(36),
	MEDECINE_ID INTEGER
);

CREATE TABLE MEDECINES (
	MEDECINE_ID INTEGER PRIMARY KEY,
	MEDECINE_DCI VARCHAR(500) NOT NULL,
	MEDECINE_MARK VARCHAR(500) NOT NULL,
	MEDECINE_FORM VARCHAR(500) NOT NULL,
	MEDECINE_DOSAGE VARCHAR(500) NOT NULL,
	MEDECINE_REDEEMABILITY BOOLEAN
);